"use strict";
var config = require("config");
var Parse = require("parse/node");
var PARSE_APP_ID = config.get('PARSE_APP_ID');
var PARSE_SERVER_URL = config.get('PARSE_SERVER_URL');
console.log('***Initialize Parse***');
console.log(PARSE_SERVER_URL);
console.log(PARSE_APP_ID);
Parse.initialize(PARSE_APP_ID);
Parse.serverURL = PARSE_SERVER_URL;
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Parse;
